[package]
name = "library"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
platform = { path = "../platform" }
heapless = { workspace = true }
postcard  = { workspace = true }
crc32fast = { workspace = true }
serde     = { version = "1", default-features = false, features = ["derive"] }

[dev-dependencies]
tempfile = "3"
tokio = { workspace = true }
criterion = { workspace = true }
platform = { path = "../platform", features = ["std"] }

[features]
default = []
std = []

[lints]
workspace = true

[[bench]]
name = "soul_library"
harness = false
